version: "3"

services:
  sonarqube:
    image: sonarqube:7.1
    container_name: sonarqube
    ports:
      - 9000:9000
    restart: always
    networks:
      - sonarnet
    environment:
    - sonar.jdbc.username=sonar
    - sonar.jdbc.password=sonar
    - sonar.jdbc.url=jdbc:postgresql://postgres:5432/postgres
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions

  postgres:
    image: postgres:10.4
    container_name: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgredb:/var/lib/postgresql/data

volumes:
  postgredb:
  sonar_data:
  sonar_extensions:
  
networks:
  sonarnet:
